#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     ultrasonicSensor, sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int lightGrade;
	long redVal;
	long greenVal;
	long blueVal;
	long intensity;
	float ultGrade;
	while (true) {
		ultGrade = getUSDistance(ultrasonicSensor);
		lightGrade = getColorReflected(colorSensor);
		getColorRGB(colorSensor, redVal, greenVal, blueVal);
		int col = 0;
		displayStringAt(20, 100 - (col++)*8, "%s%d", "Light grade: ", lightGrade);
		displayStringAt(20, 100 - (col++)*8, "%s%d", "Red value: ", redVal);
		displayStringAt(20, 100 - (col++)*8, "%s%d", "Green value: ", greenVal);
		displayStringAt(20, 100 - (col++)*8, "%s%d", "Blue value: ", blueVal);
		displayStringAt(20, 100 - (col++)*8, "%s%d", "Ultrasonic distance: ", ultGrade);

	}
}
