#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     ultrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          pinchMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Motor speeds
const int DEFAULT = 40;
const int MAX = 100;
const int MIN = 0;

//negative value makes the robot move forward
//set speed for both wheels
void setSpeed(int speed) {
	setMotorSpeed(leftMotor, -speed);
	setMotorSpeed(rightMotor, -speed);
}

void turnLeft(int diff) {
	int leftSpeed = DEFAULT + diff;
	int rightSpeed = DEFAULT - diff;
	setMotorSpeed(leftMotor, -leftSpeed);
	setMotorSpeed(rightMotor, -rightSpeed);
}

void turnRight(int diff) {
	int rightSpeed = DEFAULT + diff;
	int leftSpeed = DEFAULT - diff;
	setMotorSpeed(leftMotor, -leftSpeed);
	setMotorSpeed(rightMotor, -rightSpeed);
}

//move forward at default speed
void forward() {
	setSpeed(-DEFAULT);
}

//move backwards at default speed
void backward() {
	setSpeed(DEFAULT);
}

void stopMoving() {
	setSpeed(0);
}

//turn on brake mode for both wheels
void brakeMode() {
	setMotorBrakeMode(leftMotor, motorBrake);
	setMotorBrakeMode(rightMotor, motorBrake);
}

//function for testing
void test() {
	forward();
	sleep(500);
	turnRight(70);
	sleep(1000);
	forward();
	turnLeft(70);
	sleep(1000);
	stopMoving();
}

//Green mode

//Blue mode

//SETPOINT and threholds
const int setpoint = 10;
const int upper = 17;
const int lower = 6;
//red values: 18 10 6

int sharpnessCalc(int error) {
	if (error > 0) {
		if (error >= (upper - setpoint)) {
			return 100;	
		} else {
			return ((error * 100) / ((upper - setpoint) * 100)) * 100;
		}
	} else {
		if (error <= (lower - setpoint)) {
			return 100;
		} else {
			return ((error * 100) / ((lower - setpoint) * 100) * 100;
		}
	}
}

void adjust(int error) {
	int sharpness = sharpnessCalc(error);
	if (error < 0) {
		turnLeft(sharpness);	
	} else if (error == 0) {
		forward();
	} else {
		turnRight(sharpness);
	}
}


bool finish = false;

//STOP CONDITION : If robot turns for longer than it takes to make a 90 degree turn, finish = true


//MAIN FUNCTION
task main()
{
	int redVal;
	int greenVal;
	int blueVal;
	float distance;

	//PID variables
	float error = 0;
	float lastError = 0;
	//float integral = 0;
	float derivative = 0;

	brakeMode();

	while (!finish) {
		getColorRGB(colorSensor, redVal, greenVal, blueVal);
		
		//distance check first
		//If within 10cm, do a color check
		//if not in distance, keep adjusting/moving forward
		distance = getUSDistance(ultrasonicSensor);
		if (distance <= 10) {
				stopMoving();
				finish = true;
		}
		
		//more red = sensor away from the line = negative value -> turn left
		//less red = sensor more on top of the line = positive value -> turn right
		error = setpoint - redVal;

		adjust(error);

		wait1Msec(20);
	}
}
