#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S2,     ultrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          pinchMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int DEFAULT_SPEED = -20;

void setSpeed(int speed) {
	setMotorSpeed(leftMotor, speed);
	setMotorSpeed(rightMotor, speed);
}

void forward() {
	setSpeed(DEFAULT_SPEED);
}

void backward() {
	setSpeed(-DEFAULT_SPEED);
}

void stopMoving() {
	setSpeed(0);
}

void brakeMode() {
	setMotorBrakeMode(leftMotor, motorBrake);
	setMotorBrakeMode(rightMotor, motorBrake);
}

void turn(int sensorDiff) {
	if (sensorDiff < 0) {
		setMotorSpeed(rightMotor, DEFAULT_SPEED * 2);
	} else if (sensorDiff > 0) {
		setMotorSpeed(leftMotor, DEFAULT_SPEED * 2);
	}
}

void test() {
	forward();
	sleep(500);
	turn(10);
	sleep(1000);
	forward();
	turn(-10);
	sleep(1000);
	stopMoving();
}

task main()
{
	//int
	//bool finish = false;
	//while (!finish) {

	//}
	test();
}
