#pragma config(Sensor, S1, colorSensor, sensorEV3_Color)
#pragma config(Sensor, S4, ultrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Motor, motorA, rightMotor, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorC, pinchMotor, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorD, leftMotor, tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//
const int baseDur = 75;
const int baseNoteDur = 5;


task main()
{
	setSoundVolume(1);
	playTone(293, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	playTone(293, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	playTone(587, baseNoteDur * 2);
	wait1Msec(baseDur * 2);
	playTone(440, baseNoteDur * 2);
	wait1Msec(baseDur * 2);
	wait1Msec(baseDur * 1);
	playTone(415, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	wait1Msec(baseDur * 1);
	playTone(392, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	wait1Msec(baseDur * 1);
	playTone(349, baseNoteDur * 2);
	wait1Msec(baseDur * 2);
	playTone(293, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	playTone(349, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	playTone(392, baseNoteDur * 1);
	wait1Msec(baseDur * 1);

	playTone(261, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	playTone(261, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	playTone(587, baseNoteDur * 2);
	wait1Msec(baseDur * 2);
	playTone(440, baseNoteDur * 2);
	wait1Msec(baseDur * 2);
	wait1Msec(baseDur * 1);
	playTone(415, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	wait1Msec(baseDur * 1);
	playTone(392, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	wait1Msec(baseDur * 1);
	playTone(349, baseNoteDur * 2);
	wait1Msec(baseDur * 2);
	playTone(293, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	playTone(349, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	playTone(392, baseNoteDur * 1);
	wait1Msec(baseDur * 1);

	playTone(247, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	playTone(247, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	playTone(587, baseNoteDur * 2);
	wait1Msec(baseDur * 2);
	playTone(440, baseNoteDur * 2);
	wait1Msec(baseDur * 2);
	wait1Msec(baseDur * 1);
	playTone(415, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	wait1Msec(baseDur * 1);
	playTone(392, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	wait1Msec(baseDur * 1);
	playTone(349, baseNoteDur * 2);
	wait1Msec(baseDur * 2);
	playTone(293, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	playTone(349, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
	playTone(392, baseNoteDur * 1);
	wait1Msec(baseDur * 1);
}
